# Generated by scripts/build_day3.py; edit lesson Markdown.
import secrets
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.keywrap import aes_key_wrap, aes_key_unwrap, InvalidUnwrap
from cryptography.exceptions import InvalidTag

def require_rejection(operation, exception):
    try:
        operation()
    except exception:
        return
    raise AssertionError('Expected rejection')

kek_old = secrets.token_bytes(32)
kek_new = secrets.token_bytes(32)
dek = secrets.token_bytes(32)
nonce = secrets.token_bytes(12)
context = b'archive:v1|tenant=acme|object=7'
plaintext = b'synthetic highly confidential archive document'
ciphertext = AESGCM(dek).encrypt(nonce, plaintext, context)
wrapped_old = aes_key_wrap(kek_old, dek)
recovered_dek = aes_key_unwrap(kek_old, wrapped_old)
assert AESGCM(recovered_dek).decrypt(nonce, ciphertext, context) == plaintext
require_rejection(lambda: aes_key_unwrap(kek_new, wrapped_old), InvalidUnwrap)
require_rejection(lambda: AESGCM(recovered_dek).decrypt(nonce, ciphertext, context + b'!'), InvalidTag)
print('PASS: envelope round trip; wrong KEK and changed context rejected')

wrapped_new = aes_key_wrap(kek_new, aes_key_unwrap(kek_old, wrapped_old))
assert aes_key_unwrap(kek_new, wrapped_new) == dek
assert AESGCM(aes_key_unwrap(kek_new, wrapped_new)).decrypt(nonce, ciphertext, context) == plaintext
# An attacker with the old KEK AND an old wrapped-DEK copy still recovers this DEK.
assert aes_key_unwrap(kek_old, wrapped_old) == dek
print('PASS: rewrap changes KEK protection, not the data ciphertext or historical copies')
print("PASS: completed session-12-key-management demonstrations")
