# Generated by scripts/build_day3.py; edit lesson Markdown.
plaintext_access = {
    'client-acme': {'document-acme'},
    'worker-acme': {'document-acme'},
    'worker-other': {'document-other'},
    'storage-reader': set(),
    'gateway-operator': set(),
    'recovery-officer': {'document-acme', 'document-other'},
}
def exposed_after_compromise(principals, model):
    exposed = set()
    for principal in principals:
        if principal not in model:
            raise ValueError('Unknown principal: model evidence is missing')
        exposed.update(model[principal])
    return exposed
assert exposed_after_compromise(['storage-reader'], plaintext_access) == set()
assert exposed_after_compromise(['worker-acme'], plaintext_access) == {'document-acme'}
assert exposed_after_compromise(['recovery-officer'], plaintext_access) == {'document-acme', 'document-other'}
print('PASS: model makes recovery authority and tenant blast radius explicit')

broader_model = {principal: set(assets) for principal, assets in plaintext_access.items()}
broader_model['worker-acme'].add('document-other')
assert exposed_after_compromise(['worker-acme'], broader_model) != exposed_after_compromise(['worker-acme'], plaintext_access)
print('PASS: broadening unwrap/data permissions expands modeled exposure')
print("PASS: completed session-14-secure-architecture demonstrations")
