# Generated by scripts/build_day3.py; edit lesson Markdown.
grants = {
    ('archive-reader', 'decrypt', 'tenant-acme'),
    ('archive-writer', 'encrypt', 'tenant-acme'),
    ('key-operator', 'rotate', 'tenant-acme'),
}
audit = []
def authorize(authenticated_principal, operation, tenant, request_id):
    allowed = (authenticated_principal, operation, tenant) in grants
    audit.append({'principal': authenticated_principal, 'operation': operation,
                  'tenant': tenant, 'request_id': request_id, 'allowed': allowed})
    return allowed

assert authorize('archive-reader', 'decrypt', 'tenant-acme', 'r1')
assert not authorize('archive-reader', 'decrypt', 'tenant-other', 'r2')
assert not authorize('key-operator', 'decrypt', 'tenant-acme', 'r3')
assert not authorize('unknown', 'decrypt', 'tenant-acme', 'r4')
assert all('plaintext' not in row and 'key_bytes' not in row for row in audit)
print('PASS: simulated policy separates tenant and operation permissions')

# The same approved identity is indistinguishable to this policy after host compromise.
assert authorize('archive-reader', 'decrypt', 'tenant-acme', 'attacker-request')
assert not authorize('archive-reader', 'rotate', 'tenant-acme', 'attacker-rotate')
print('PASS: authorized-use exposure remains, while operation scope limits other actions')
print("PASS: completed session-13-protecting-keys demonstrations")
