# Generated by scripts/build_day3.py; edit lesson Markdown.
from graphlib import TopologicalSorter, CycleError
dependencies = {
    'inventory': set(),
    'profile review': {'inventory'},
    'verifier upgrade': {'profile review'},
    'trust provisioning': {'verifier upgrade'},
    'transport pilot': {'profile review'},
    'restore rehearsal': {'trust provisioning'},
    'rollout': {'transport pilot', 'restore rehearsal'},
}
duration = {'inventory': 2, 'profile review': 1, 'verifier upgrade': 4,
            'trust provisioning': 2, 'transport pilot': 3,
            'restore rehearsal': 1, 'rollout': 2}
order = list(TopologicalSorter(dependencies).static_order())
finish = {}
for task in order:
    start = max((finish[parent] for parent in dependencies[task]), default=0)
    finish[task] = start + duration[task]
assert finish['rollout'] == 12
print('PASS: dependency plan computes a 12-month hypothetical completion path')

import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(8, 4))
for index, task in enumerate(order):
    ax.barh(index, duration[task], left=finish[task] - duration[task])
ax.set_yticks(range(len(order)), order)
ax.invert_yaxis()
ax.set(xlabel='Months from project start — invented assumptions', title='Dependency-constrained teaching plan')
fig.tight_layout()
plt.show()
broken = {task: set(parents) for task, parents in dependencies.items()}
broken['inventory'].add('rollout')
try:
    list(TopologicalSorter(broken).static_order())
except CycleError:
    pass
else:
    raise AssertionError('Dependency cycle not detected')
print('PASS: plotted assumptions and rejected circular dependencies')
print("PASS: completed session-16-pqc-migration demonstrations")
