# Generated by scripts/build_session05.py from the Session 5 lesson.

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.exceptions import InvalidSignature

alice_signer = Ed25519PrivateKey.generate()
trusted_alice = alice_signer.public_key()  # Simulated trusted provisioning.
approval = b"invoice-approval:v1|tenant=acme|invoice=7|amount=125|currency=USD"
signature = alice_signer.sign(approval)
assert len(signature) == 64
assert trusted_alice.verify(signature, approval) is None
print("PASS: Ed25519 verifies the original approval; success returns None.")

def valid_signature(public_key, message, supplied_signature):
    try:
        public_key.verify(supplied_signature, message)
    except InvalidSignature:
        return False
    return True

other_signer = Ed25519PrivateKey.generate()
changed_signature = bytes([signature[0] ^ 1]) + signature[1:]
assert valid_signature(trusted_alice, approval, signature)
assert not valid_signature(trusted_alice, approval + b"\n", signature)
assert not valid_signature(trusted_alice, approval, changed_signature)
assert not valid_signature(other_signer.public_key(), approval, signature)
assert not valid_signature(trusted_alice, approval, signature[:-1])
print("PASS: changed bytes, signature, verification key, and truncated signature fail.")

import json

record = {"tenant": "acme", "invoice": 7, "action": "approve"}
compact = json.dumps(record, sort_keys=True, separators=(",", ":")).encode("utf-8")
pretty = json.dumps(record, sort_keys=True, indent=2).encode("utf-8")
assert json.loads(compact) == json.loads(pretty)
assert compact != pretty
compact_signature = alice_signer.sign(compact)
assert valid_signature(trusted_alice, compact, compact_signature)
assert not valid_signature(trusted_alice, pretty, compact_signature)
print("PASS: equivalent JSON objects can have different signed bytes.")

mallory = Ed25519PrivateKey.generate()
forged_claim = b"invoice-approval:v1|tenant=acme|invoice=7|amount=999|currency=USD"
mallory_signature = mallory.sign(forged_claim)
assert valid_signature(mallory.public_key(), forged_claim, mallory_signature)
assert not valid_signature(trusted_alice, forged_claim, mallory_signature)
print("PASS: attacker-supplied key accepts its own signature but fails under trusted Alice key.")

import hashlib

release_signer = Ed25519PrivateKey.generate()
trusted_release = release_signer.public_key()
artifact = b"synthetic firmware image for workshop only"
manifest = {
    "purpose": "firmware-release:v1", "product": "training-device",
    "version": 8, "length": len(artifact),
    "sha256": hashlib.sha256(artifact).hexdigest(),
}
manifest_bytes = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode("utf-8")
manifest_signature = release_signer.sign(manifest_bytes)
assert valid_signature(trusted_release, manifest_bytes, manifest_signature)
assert hashlib.sha256(artifact).hexdigest() == manifest["sha256"]
assert hashlib.sha256(artifact + b"changed").hexdigest() != manifest["sha256"]
print("PASS: signed manifest binds the digest; modified artifact fails the digest check.")

def unique_fields(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("Duplicate manifest field")
        result[key] = value
    return result

def accept_release(data, sig, payload, expected_product, minimum_version):
    if len(data) > 4096 or not valid_signature(trusted_release, data, sig):
        return False
    try:
        item = json.loads(data, object_pairs_hook=unique_fields)
    except (ValueError, UnicodeDecodeError):
        return False
    if type(item) is not dict or set(item) != {"purpose", "product", "version", "length", "sha256"}:
        return False
    if type(item["version"]) is not int or type(item["length"]) is not int:
        return False
    return (
        item["purpose"] == "firmware-release:v1"
        and item["product"] == expected_product
        and item["version"] >= minimum_version
        and item["length"] == len(payload)
        and item["sha256"] == hashlib.sha256(payload).hexdigest()
    )

assert accept_release(manifest_bytes, manifest_signature, artifact, "training-device", 8)
assert not accept_release(manifest_bytes, manifest_signature, artifact + b"!", "training-device", 8)
assert not accept_release(manifest_bytes, manifest_signature, artifact, "other-device", 8)
assert not accept_release(manifest_bytes, manifest_signature, artifact, "training-device", 9)
assert not accept_release(manifest_bytes, mallory.sign(manifest_bytes), artifact, "training-device", 8)
# Authentic bytes need not form a valid manifest.
bad_schema = b'{"version":true}'
assert not accept_release(bad_schema, release_signer.sign(bad_schema), artifact, "training-device", 8)
for invalid_manifest in [dict(manifest, version=True), dict(manifest, purpose="invoice-approval:v1")]:
    invalid_bytes = json.dumps(invalid_manifest).encode("utf-8")
    assert not accept_release(invalid_bytes, release_signer.sign(invalid_bytes), artifact, "training-device", 8)
duplicate_field = manifest_bytes[:-1] + b',"version":8}'
assert not accept_release(duplicate_field, release_signer.sign(duplicate_field), artifact, "training-device", 8)
print("PASS: release policy rejects tampering, wrong product, rollback, impostor, and bad schema.")

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, rsa, padding

ecdsa_signer = ec.generate_private_key(ec.SECP256R1())
ecdsa_signature = ecdsa_signer.sign(approval, ec.ECDSA(hashes.SHA256()))
ecdsa_signer.public_key().verify(ecdsa_signature, approval, ec.ECDSA(hashes.SHA256()))
rsa_signer = rsa.generate_private_key(public_exponent=65537, key_size=3072)
pss = padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=32)
rsa_signature = rsa_signer.sign(approval, pss, hashes.SHA256())
rsa_signer.public_key().verify(rsa_signature, approval, pss, hashes.SHA256())
for verify_changed in [
    lambda: ecdsa_signer.public_key().verify(ecdsa_signature, approval + b"!", ec.ECDSA(hashes.SHA256())),
    lambda: rsa_signer.public_key().verify(rsa_signature, approval + b"!", pss, hashes.SHA256()),
]:
    try:
        verify_changed()
    except InvalidSignature:
        pass
    else:
        raise AssertionError("Changed message unexpectedly accepted")
print("PASS: ECDSA and RSA-PSS verify original bytes and reject changed messages.")
