# Generated by scripts/build_session03.py from the Session 3 lesson.

import hashlib

document = b"invoice=7;amount=125;currency=USD"
digest = hashlib.sha256(document).digest()
assert len(digest) == 32
assert len(digest.hex()) == 64
assert hashlib.sha256(document).digest() == digest
assert hashlib.sha256(document + b"\n").digest() != digest
assert len(hashlib.sha3_256(document).digest()) == 32
assert hashlib.sha3_256(document).digest() != digest
print("PASS: hashes are deterministic; exact bytes and algorithm matter.")

changed_document = b"invoice=7;amount=999;currency=USD"
attacker_supplied_digest = hashlib.sha256(changed_document).digest()
assert hashlib.sha256(changed_document).digest() == attacker_supplied_digest
print("OBSERVE: a modified file agrees with the attacker's replacement digest.")

import hmac
import secrets

mac_key = secrets.token_bytes(32)
event = b"invoice-event:v1|tenant=acme|record=invoice-7|action=approved"
tag = hmac.digest(mac_key, event, "sha256")

def verify_event(key, message, supplied_tag):
    expected = hmac.digest(key, message, "sha256")
    return hmac.compare_digest(expected, supplied_tag)

assert verify_event(mac_key, event, tag)
assert not verify_event(mac_key, event.replace(b"acme", b"other"), tag)
assert not verify_event(secrets.token_bytes(32), event, tag)
assert not verify_event(mac_key, event, tag[:-1])
print("PASS: original HMAC verifies; changed message, key, and tag are rejected.")

toy_password = "lab-only-password-123"
weak_verifier = hashlib.sha256(toy_password.encode("utf-8")).digest()
toy_guesses = ["wrong-first-guess", "lab-only-password-123", "another-guess"]
found = next((guess for guess in toy_guesses
              if hashlib.sha256(guess.encode("utf-8")).digest() == weak_verifier), None)
assert found == toy_password
print("OBSERVE: the fabricated password was found by hashing a small guess list.")

from argon2 import PasswordHasher, Type
from argon2.exceptions import VerifyMismatchError

password_hasher = PasswordHasher(
    time_cost=3, memory_cost=65536, parallelism=4,
    hash_len=32, salt_len=16, type=Type.ID,
)
demo_password = "demonstration-only-not-a-real-account-password"
stored_verifier = password_hasher.hash(demo_password)
second_verifier = password_hasher.hash(demo_password)
assert stored_verifier.startswith("$argon2id$")
assert stored_verifier != second_verifier
assert password_hasher.verify(stored_verifier, demo_password)

try:
    password_hasher.verify(stored_verifier, "wrong-password")
except VerifyMismatchError:
    print("PASS: wrong password rejected.")
else:
    raise AssertionError("Wrong password unexpectedly accepted")

assert not password_hasher.check_needs_rehash(stored_verifier)
print("PASS: fresh salts produce different records; the correct password verifies.")

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

input_secret = secrets.token_bytes(32)
derivation_salt = secrets.token_bytes(32)

def derive_demo_key(secret, salt, context):
    return HKDF(algorithm=hashes.SHA256(), length=32,
                salt=salt, info=context).derive(secret)

label_ab = b"workshop:v1:alice-to-bob:aead"
label_ba = b"workshop:v1:bob-to-alice:aead"
key_ab = derive_demo_key(input_secret, derivation_salt, label_ab)
key_ba = derive_demo_key(input_secret, derivation_salt, label_ba)
assert key_ab == derive_demo_key(input_secret, derivation_salt, label_ab)
assert key_ab != key_ba
assert key_ab != derive_demo_key(input_secret, secrets.token_bytes(32), label_ab)
assert len(key_ab) == 32
print("PASS: matching HKDF inputs reproduce a key; different contexts separate outputs.")

from cryptography.exceptions import InvalidTag
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

traffic_nonce = secrets.token_bytes(12)
traffic_aad = b"workshop:v1:invoice-7:alice-to-bob"
protected = AESGCM(key_ab).encrypt(traffic_nonce, document, traffic_aad)
receiver_key = derive_demo_key(input_secret, derivation_salt, label_ab)
assert AESGCM(receiver_key).decrypt(traffic_nonce, protected, traffic_aad) == document
try:
    AESGCM(key_ba).decrypt(traffic_nonce, protected, traffic_aad)
except InvalidTag:
    print("PASS: using the opposite-direction key rejects the message.")
else:
    raise AssertionError("Wrong directional key unexpectedly accepted")

new_random_key = secrets.token_bytes(32)
new_public_nonce = secrets.token_bytes(12)
reset_token = secrets.token_urlsafe(32)
assert len(new_random_key) == 32
assert len(new_public_nonce) == 12
print("PASS: generated key, nonce, and token without printing their values.")
