"""Generate Session 3's notebook and Python demo from its Markdown lesson."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
NAME = 'session-03-hashes-passwords-kdfs'


def render(session=3):
    lesson = {3: '03-hashes-passwords-kdfs', 4: '04-classical-public-key',
              5: '05-digital-signatures'}[session]
    name = 'session-' + lesson
    source = (ROOT / 'docs/day-1' / (lesson + '.md')).read_text(encoding='utf-8')
    cells, examples = [], []

    def add(kind, content):
        if not content.strip():
            return
        if kind == 'markdown':
            content = re.sub(r'\[([^\]]+)\]\((?!https?://)([^)]+)\)', r'\1 (see course website)', content)
        cell = dict(cell_type=kind, id=f'session{session:02d}-{len(cells):03d}', metadata={},
                    source=(content.strip() + '\n').splitlines(keepends=True))
        if kind == 'code':
            cell.update(execution_count=None, outputs=[])
        cells.append(cell)

    add('markdown', f'# Session {session} experimental companion\n\nRun cells in order. Use only synthetic data. Mermaid diagrams render on the course website; their source is retained below. Setup installs the pinned teaching dependencies in this notebook runtime.')
    add('code', '''import importlib.metadata
import subprocess
import sys

for package, version in {"cryptography": "50.0.1", "argon2-cffi": "25.1.0"}.items():
    try:
        installed = importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        installed = None
    if installed != version:
        subprocess.check_call([sys.executable, "-m", "pip", "install", f"{package}=={version}"])
print("Dependencies ready. If replacing an already imported library, restart the runtime and run all cells.")''')
    if session != 3:
        cells[1]['source'] = [line.replace(', "argon2-cffi": "25.1.0"', '') for line in cells[1]['source']]
    cursor = 0
    for match in re.finditer(r'^```python\n(.*?)\n```[ \t]*$', source, re.M | re.S):
        add('markdown', source[cursor:match.start()])
        add('code', match.group(1))
        examples.append(match.group(1))
        cursor = match.end()
    add('markdown', source[cursor:])
    notebook = dict(cells=cells, metadata={
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python'}, 'colab': {'name': name + '.ipynb', 'provenance': []},
    }, nbformat=4, nbformat_minor=5)
    demo = f'# Generated by scripts/build_session{session:02d}.py from the Session {session} lesson.\n\n' + '\n\n'.join(examples) + '\n'
    return json.dumps(notebook, ensure_ascii=False, indent=2) + '\n', demo


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    notebook, demo = render()
    for relative, expected in [(f'notebooks/{NAME}.ipynb', notebook),
                               (f'docs/downloads/{NAME}.ipynb', notebook),
                               ('examples/session-03/demo.py', demo)]:
        path = ROOT / relative
        if args.check:
            assert path.exists() and path.read_text(encoding='utf-8') == expected, f'Stale: {relative}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding='utf-8')
    print('PASS: Session 3 notebook, website download, and demo synchronized.')


if __name__ == '__main__':
    main()
