"""Generate Day 3 companions from authoritative lesson Markdown."""
import argparse
import csv
import io
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LESSONS = ['12-key-management', '13-protecting-keys', '14-secure-architecture',
           '15-crypto-agility', '16-pqc-migration']
DAY3_NAMES = ['session-' + slug for slug in LESSONS]
SETUP = '''import importlib.metadata
import subprocess
import sys
for package, version in {"cryptography": "50.0.1", "matplotlib": "3.10.6"}.items():
    try:
        installed = importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        installed = None
    if installed != version:
        subprocess.check_call([sys.executable, '-m', 'pip', 'install', f'{package}=={version}'])
print('Dependencies ready. Restart if an older library was already imported.')
'''


def portable(text):
    return re.sub(r'\[([^\]]+)\]\((?!https?://)([^)]+)\)', r'\1 (see course website)', text)


def outputs():
    for slug, name in zip(LESSONS, DAY3_NAMES):
        source = (ROOT / f'docs/day-3/{slug}.md').read_text(encoding='utf-8')
        cells, code = [], []

        def add(kind, content):
            if not content.strip():
                return
            if kind == 'markdown':
                content = portable(content)
            cell = dict(cell_type=kind, id=f'day3-{len(cells):03d}', metadata={},
                        source=(content.strip() + '\n').splitlines(keepends=True))
            if kind == 'code':
                cell.update(execution_count=None, outputs=[])
            cells.append(cell)

        add('markdown', '# Day 3 notebook companion\n\nRun in order with synthetic data. Predict results before executing, then change inputs and explain the effect. Mermaid diagrams render on the website. This notebook includes its dependencies and requires no checkout or cloud credentials.')
        add('code', SETUP)
        cursor = 0
        for match in re.finditer(r'^```python\n(.*?)\n```[ \t]*$', source, re.M | re.S):
            add('markdown', source[cursor:match.start()])
            add('code', match.group(1))
            code.append(match.group(1))
            cursor = match.end()
        add('markdown', source[cursor:])
        finish = f'print("PASS: completed {name} demonstrations")'
        add('code', finish)
        notebook = dict(cells=cells, metadata={
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python'}, 'colab': {'name': name + '.ipynb', 'provenance': []},
        }, nbformat=4, nbformat_minor=5)
        rendered = json.dumps(notebook, ensure_ascii=False, indent=2) + '\n'
        yield f'notebooks/{name}.ipynb', rendered
        yield f'docs/downloads/{name}.ipynb', rendered
        yield f'examples/session-{slug[:2]}/demo.py', '# Generated by scripts/build_day3.py; edit lesson Markdown.\n' + '\n\n'.join(code) + '\n' + finish + '\n'
    yield 'docs/downloads/capstone-worksheet.md.txt', portable((ROOT / 'docs/capstone/worksheet.md').read_text(encoding='utf-8'))
    buffer = io.StringIO(newline='')
    writer = csv.writer(buffer, lineterminator='\n')
    writer.writerow(['Asset/flow', 'Plaintext locations', 'Crypto role and profile', 'Key/trust owner', 'Lifetime and copies', 'Evidence / unknowns'])
    for asset in ['User upload', 'Internal API', 'Document objects', 'Database metadata', 'Search index', 'Queue', 'Backups and reader', 'Signed updates']:
        writer.writerow([asset] + [''] * 5)
    yield 'docs/downloads/capstone-inventory.csv', buffer.getvalue()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for relative, expected in outputs():
        target = ROOT / relative
        if args.check:
            assert target.exists() and target.read_text(encoding='utf-8') == expected, f'Stale: {relative}'
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding='utf-8')
    print('PASS: five Day 3 notebooks, demos and capstone downloads synchronized')


if __name__ == '__main__':
    main()
