"""Generate Day 2 notebooks and local scripts from Markdown plus shared helpers."""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
LESSONS = ['06-pki-certificates', '07-tls', '08-quantum-threat', '09-ml-kem',
           '10-hybrid-key-establishment', '11-ml-dsa']
LABS = ['04-mini-pki', '05-pqc-channel', '06-pqc-signatures']
DAY2_NAMES = ['session-' + x for x in LESSONS] + ['lab-' + x for x in LABS]
SETUP = '''import importlib.metadata
import subprocess
import sys
for package, version in {"cryptography": "50.0.1", "matplotlib": "3.10.6", "ipywidgets": "8.1.7"}.items():
    try:
        installed = importlib.metadata.version(package)
    except importlib.metadata.PackageNotFoundError:
        installed = None
    if installed != version:
        subprocess.check_call([sys.executable, "-m", "pip", "install", f"{package}=={version}"])
print("Dependencies ready. Restart if an older library was already imported, then run all cells.")
'''


def outputs():
    helper = (ROOT / 'src/crypto_workshop/day2.py').read_text(encoding='utf-8')
    yield 'docs/downloads/day2_helpers.py', helper
    for name in DAY2_NAMES:
        is_lab = name.startswith('lab-')
        slug = name.removeprefix('session-')
        page = ('docs/labs/' if is_lab else 'docs/day-2/') + slug + '.md'
        source = (ROOT / page).read_text(encoding='utf-8').replace('<!-- day2:helpers -->', '')
        cells, code = [], []

        def add(kind, content):
            if not content.strip():
                return
            if kind == 'markdown':
                content = re.sub(r'\[([^\]]+)\]\((?!https?://)([^)]+)\)', r'\1 (see course website)', content)
            cell = dict(cell_type=kind, id=f'day2-{len(cells):03d}', metadata={},
                        source=(content.strip() + '\n').splitlines(keepends=True))
            if kind == 'code':
                cell.update(execution_count=None, outputs=[])
            cells.append(cell)

        add('markdown', '# Day 2 notebook companion\n\nRun in order with synthetic data. Mermaid diagrams render on the website. Setup and shared helpers are embedded; no checkout is required. Learner exercises report NOT ATTEMPTED until implemented. Reference checks are separate. Optional controls also have direct function calls.')
        add('code', SETUP)
        add('markdown', '## Shared teaching helpers\n\nInspect this implementation. TLS uses real SSL objects over memory buffers and temporary test key files; no system trust changes or network listeners. The teaching KDF is not a standardized protocol key schedule.')
        add('code', helper)
        cursor = 0
        for match in re.finditer(r'^```python\n(.*?)\n```[ \t]*$', source, re.M | re.S):
            add('markdown', source[cursor:match.start()])
            add('code', match.group(1))
            code.append(match.group(1))
            cursor = match.end()
        add('markdown', source[cursor:])
        finish = f'print("PASS: completed {name} demonstrations; learner status is reported separately")'
        add('code', finish)
        notebook = dict(cells=cells, metadata={
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python'}, 'colab': {'name': name + '.ipynb', 'provenance': []},
        }, nbformat=4, nbformat_minor=5)
        rendered = json.dumps(notebook, ensure_ascii=False, indent=2) + '\n'
        yield f'notebooks/{name}.ipynb', rendered
        yield f'docs/downloads/{name}.ipynb', rendered
        local = f'labs/{name}/starter.py' if is_lab else f'examples/session-{slug[:2]}/demo.py'
        yield local, '# Generated by scripts/build_day2.py; edit the Markdown source.\n' + helper + '\n\n' + '\n\n'.join(code) + '\n' + finish + '\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for relative, expected in outputs():
        target = ROOT / relative
        if args.check:
            assert target.exists() and target.read_text(encoding='utf-8') == expected, f'Stale: {relative}'
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected, encoding='utf-8')
    print('PASS: nine Day 2 notebooks, downloads and local scripts synchronized')


if __name__ == '__main__':
    main()
