# Generated by scripts/build_day3.py; edit lesson Markdown.
profiles = {'record-v1': 'legacy-reader', 'record-v2': 'current-provider'}
policy = {'write': 'record-v2', 'read': frozenset({'record-v1', 'record-v2'})}
def select_profile(requested, operation, config):
    if requested not in profiles:
        raise ValueError('Unknown profile')
    if operation == 'write' and requested == config['write']:
        return profiles[requested]
    if operation == 'read' and requested in config['read']:
        return profiles[requested]
    raise ValueError('Profile or operation disallowed')

def expect_policy_rejection(operation):
    try:
        operation()
    except ValueError:
        return
    raise AssertionError('Policy unexpectedly accepted')

assert select_profile('record-v1', 'read', policy) == 'legacy-reader'
assert select_profile('record-v2', 'write', policy) == 'current-provider'
expect_policy_rejection(lambda: select_profile('record-v1', 'write', policy))
expect_policy_rejection(lambda: select_profile('none', 'read', policy))
expect_policy_rejection(lambda: select_profile('record-v2', 'decrypt-anything', policy))
print('PASS: old reads and new writes are distinct; unknown modes reject')

def can_retire(evidence):
    required = {'live_records_migrated', 'backups_recoverable', 'clients_ready',
                'restore_test_passed', 'owner_approved'}
    return set(evidence) == required and all(value is True for value in evidence.values())

evidence = dict.fromkeys(['live_records_migrated', 'backups_recoverable', 'clients_ready',
                          'restore_test_passed', 'owner_approved'], True)
assert can_retire(evidence)
assert not can_retire(dict(evidence, backups_recoverable=False))
assert not can_retire(dict(evidence, owner_approved='yes'))
retired_policy = {'write': 'record-v2', 'read': frozenset({'record-v2'})}
expect_policy_rejection(lambda: select_profile('record-v1', 'read', retired_policy))
print('PASS: retirement requires explicit evidence and removes legacy acceptance')
print("PASS: completed session-15-crypto-agility demonstrations")
