# Generated by scripts/build_day2.py; edit the Markdown source.
"""Day 2 teaching helpers. Real TLS over MemoryBIO; no sockets or trust-store changes."""
from datetime import datetime, timedelta, timezone
from pathlib import Path
import ssl
import tempfile
import hashlib
from cryptography import x509
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives.kdf.hkdf import HKDF


def make_pki(expired=False):
    """Create an isolated root, intermediate, server, and client for this run."""
    now = datetime.now(timezone.utc)
    keys = {name: ec.generate_private_key(ec.SECP256R1())
            for name in ('root', 'intermediate', 'server', 'client')}
    names = {name: x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, 'Workshop ' + name)])
             for name in keys}
    certs = {}
    for name, issuer, ca, path_length, eku in [
        ('root', 'root', True, 1, None),
        ('intermediate', 'root', True, 0, None),
        ('server', 'intermediate', False, None, ExtendedKeyUsageOID.SERVER_AUTH),
        ('client', 'intermediate', False, None, ExtendedKeyUsageOID.CLIENT_AUTH),
    ]:
        end = now - timedelta(days=1) if expired and name == 'server' else now + timedelta(days=7)
        builder = (x509.CertificateBuilder().subject_name(names[name]).issuer_name(names[issuer])
                   .public_key(keys[name].public_key()).serial_number(x509.random_serial_number())
                   .not_valid_before(now - timedelta(days=2)).not_valid_after(end)
                   .add_extension(x509.BasicConstraints(ca=ca, path_length=path_length), critical=True)
                   .add_extension(x509.KeyUsage(digital_signature=True, content_commitment=False,
                       key_encipherment=False, data_encipherment=False, key_agreement=False,
                       key_cert_sign=ca, crl_sign=ca, encipher_only=False, decipher_only=False), critical=True)
                   .add_extension(x509.SubjectKeyIdentifier.from_public_key(keys[name].public_key()), False)
                   .add_extension(x509.AuthorityKeyIdentifier.from_issuer_public_key(keys[issuer].public_key()), False))
        if eku:
            builder = builder.add_extension(x509.ExtendedKeyUsage([eku]), False)
            builder = builder.add_extension(x509.SubjectAlternativeName([
                x509.DNSName('invoice.test' if name == 'server' else 'client.test')]), False)
        certs[name] = builder.sign(keys[issuer], hashes.SHA256())
    return keys, certs


def tls_trial(hostname='invoice.test', trust_root=True, expired=False,
              include_intermediate=True, mtls=False, send_client=True,
              client_wrong_eku=False):
    """Handshake and exchange application bytes. Failures raise ssl.SSLError.

    Private PEM files are disposable teaching keys in a temporary directory.
    Does not implement online revocation, networking, or authorization policy.
    """
    keys, certs = make_pki(expired)
    pem = lambda c: c.public_bytes(serialization.Encoding.PEM)
    with tempfile.TemporaryDirectory(prefix='workshop-pki-') as directory:
        base = Path(directory)
        for name in ('server', 'client'):
            selected = 'server' if name == 'client' and client_wrong_eku else name
            chain = pem(certs[selected])
            if include_intermediate or name == 'client':
                chain += pem(certs['intermediate'])
            (base / (name + '.pem')).write_bytes(chain)
            (base / (name + '.key')).write_bytes(keys[selected].private_bytes(
                serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                serialization.NoEncryption()))
        server_context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        client_context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        for context in (server_context, client_context):
            context.minimum_version = context.maximum_version = ssl.TLSVersion.TLSv1_3
        server_context.load_cert_chain(str(base / 'server.pem'), str(base / 'server.key'))
        if trust_root:
            client_context.load_verify_locations(cadata=pem(certs['root']).decode())
        if mtls:
            server_context.verify_mode = ssl.CERT_REQUIRED
            server_context.load_verify_locations(cadata=pem(certs['root']).decode())
        if send_client:
            client_context.load_cert_chain(str(base / 'client.pem'), str(base / 'client.key'))
        ci, co, si, so = (ssl.MemoryBIO() for _ in range(4))
        client = client_context.wrap_bio(ci, co, server_hostname=hostname)
        server = server_context.wrap_bio(si, so, server_side=True)
        completed = [False, False]

        def transfer():
            for outgoing, incoming in ((co, si), (so, ci)):
                if outgoing.pending:
                    incoming.write(outgoing.read())

        for _ in range(100):
            for index, peer in enumerate((client, server)):
                if not completed[index]:
                    try:
                        peer.do_handshake()
                        completed[index] = True
                    except ssl.SSLWantReadError:
                        pass
            transfer()
            if all(completed):
                break
        else:
            raise RuntimeError('TLS handshake stalled')
        payload = b'synthetic confidential invoice'
        client.write(payload)
        transfer()
        assert server.read(4096) == payload
        return {'version': client.version(), 'cipher': client.cipher()[0],
                'client_authenticated': bool(server.getpeercert()),
                'application_bytes': len(payload)}


def expect_rejection(operation, exceptions):
    """Assert the negative case, without accepting a silent failure."""
    try:
        operation()
    except exceptions:
        return
    raise AssertionError('Expected rejection did not occur')


def derive_day2(secret, transcript, direction=b'alice-to-bob'):
    """Teaching KDF only, not a standardized TLS or hybrid key schedule."""
    return HKDF(algorithm=hashes.SHA256(), length=32, salt=None,
                info=b'workshop-day2:v1|' + hashlib.sha256(transcript).digest()
                + b'|' + direction).derive(secret)


"""Interactive teaching experiments. Cryptographic operations and policy models are labelled.

Uses the lesson's already-executed namespace; does not contact external services.
"""
import hashlib
from html import escape

TEACHING_CASES = {
    7: ['valid', 'wrong-hostname', 'unknown-root', 'mutual-tls', 'missing-client', 'wrong-client-purpose'],
    8: ['archive', 'research', 'telemetry'],
    9: ['valid', 'altered-kem-ciphertext', 'truncated-kem-ciphertext', 'wrong-recipient', 'changed-aad'],
    10: ['valid', 'zero-pq-contribution', 'changed-transcript', 'missing-contribution', 'downgrade', 'unauthenticated'],
    11: ['valid', 'changed-message', 'changed-context', 'wrong-key', 'truncated-signature', 'old-version'],
    12: ['valid', 'wrong-kek', 'changed-context', 'rewrap', 'stolen-old-backup'],
    13: ['valid', 'wrong-tenant', 'operator-decrypt', 'compromised-reader', 'revoked-grant'],
    14: ['storage-reader', 'worker-acme', 'recovery-officer', 'broaden-worker', 'unknown-principal'],
    15: ['valid', 'legacy-read', 'legacy-write', 'unknown-profile', 'backup-not-ready', 'retire'],
    16: ['baseline', 'verifier-delay', 'transport-delay', 'cycle'],
}


def teaching_step(name, explanation, artifacts=None, status='OBSERVE'):
    return {'step':name, 'status':status, 'explanation':explanation, 'artifacts':artifacts or {}}


def teaching_steps(session, ns, case='valid', parameter=10):
    """Lazy generator: Next step executes the next operation, not just reveals text."""
    if session not in TEACHING_CASES or case not in TEACHING_CASES[session]:
        raise ValueError('Unknown session or case')
    def step(name, explanation, artifacts=None, status='OBSERVE'):
        return teaching_step(name, explanation, artifacts, status)
    if session == 7:
        import ssl
        options = {'wrong-hostname':{'hostname':'other.test'}, 'unknown-root':{'trust_root':False},
                   'mutual-tls':{'mtls':True}, 'missing-client':{'mtls':True,'send_client':False},
                   'wrong-client-purpose':{'mtls':True,'client_wrong_eku':True}}.get(case,{})
        yield step('Configure endpoints', 'Real TLS 1.3 via MemoryBIO. Verification remains enabled.', {'options':(options,False)})
        try:
            result = ns['tls_trial'](**options)
        except ssl.SSLError as error:
            yield step('TLS handshake', str(error), status='REJECT'); return
        yield step('TLS handshake and record', 'This is a whole real handshake, not a packet-by-packet trace.', {'negotiated/result':(result,False)},'PASS')
        yield step('Interpret result', 'Cipher suite does not identify the key-exchange group. mTLS identity still needs application authorization.', status='LIMIT')
    elif session == 8:
        asset = {'archive':(20,5),'research':(10,3),'telemetry':(1,2)}[case]
        lifetime, migration = asset
        yield step('Assumptions', 'Hypothetical years, not a forecast.', {'L, M, H':((lifetime,migration,parameter),False)})
        gap = ns['planning_gap'](lifetime,migration,parameter)
        yield step('Compute L + M - H', f'{lifetime} + {migration} - {parameter} = {gap}', status='GAP' if gap>0 else 'NO POSITIVE GAP')
        yield step('Bound the claim', 'Zero/negative gap does not prove safety, remove existing recordings or address endpoint compromise.', status='LIMIT')
    elif session == 9:
        from cryptography.hazmat.primitives.asymmetric.mlkem import MLKEM768PrivateKey
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        from cryptography.exceptions import InvalidTag
        import secrets
        bob = ns['bob_kem']
        secret, ct = bob.public_key().encapsulate()
        yield step('Encapsulate to Bob', 'Inspect public encapsulation key, KEM ciphertext and locally generated secret.',
                   {'public key':(bob.public_key().public_bytes_raw(),False),'KEM ciphertext':(ct,False),'sender secret':(secret,True)})
        received = ct[:-1] if case=='truncated-kem-ciphertext' else bytes([ct[0]^1])+ct[1:] if case=='altered-kem-ciphertext' else ct
        recipient = MLKEM768PrivateKey.generate() if case=='wrong-recipient' else bob
        try:
            recovered = recipient.decapsulate(received)
        except ValueError:
            yield step('Decapsulate', 'Wrong-length ciphertext rejected as malformed.',status='REJECT'); return
        yield step('Decapsulate', f'Returned {len(recovered)} bytes; equal secrets = {secret == recovered}. Returning bytes is not peer authentication.', {'receiver secret':(recovered,True)})
        transcript = b'panel:ML-KEM-768:v1|' + bob.public_key().public_bytes_raw() + ct
        sender_key, receiver_key = (ns['derive_day2'](s,transcript) for s in (secret,recovered))
        yield step('Derive record keys', 'Hold original transcript fixed to isolate secret mismatch; this is a teaching schedule.', {'sender key':(sender_key,True),'receiver key':(receiver_key,True)})
        nonce, aad = secrets.token_bytes(12), b'invoice-panel:v1'
        record = AESGCM(sender_key).encrypt(nonce,b'synthetic invoice',aad)
        try:
            plaintext = AESGCM(receiver_key).decrypt(nonce,record,aad+b'!' if case=='changed-aad' else aad)
        except InvalidTag:
            yield step('Authenticate record', 'AEAD rejected; no plaintext released.',{'AEAD record':(record,False)},'REJECT'); return
        yield step('Authenticate record', 'Round trip succeeds. Identity and replay protection remain protocol requirements.',{'plaintext':(plaintext,False)},'PASS')
    elif session == 10:
        selected = 'classical-only' if case=='downgrade' else 'approved-hybrid-profile'
        yield step('Negotiation inputs', 'Application policy model, not authenticated wire negotiation.',{'selected profile':(selected,False)})
        try:
            ns['require_hybrid'](selected,case!='unauthenticated')
        except ValueError as error:
            yield step('Minimum policy', str(error),status='REJECT'); return
        yield step('Contributions', 'Fixed-size classical and PQ secrets from the lesson.', {'classical':(ns['zx_a'],True),'PQ':(ns['zp_a'],True)})
        pq = b'' if case=='missing-contribution' else bytes(32) if case=='zero-pq-contribution' else ns['zp_a']
        context = ns['transcript'] + (b'changed' if case=='changed-transcript' else b'')
        try:
            key = ns['teaching_combiner'](ns['zx_a'],pq,context)
        except ValueError as error:
            yield step('Combiner', str(error),status='REJECT'); return
        yield step('Compare output', f'Matches baseline = {key == ns["key_a"]}. Sensitivity is not a robust-combiner proof; zeros are not a fallback.', {'derived key':(key,True)},'OBSERVE')
    elif session == 11:
        from cryptography.hazmat.primitives.asymmetric.mldsa import MLDSA65PrivateKey
        from cryptography.exceptions import InvalidSignature
        message = ns['message'].replace(b'version=9',b'version=8') if case=='old-version' else ns['message']
        signature = ns['signer'].sign(message,ns['context'])
        yield step('Sign exact release bytes', 'This signature binds message and context; public key trust is configured separately.', {'message':(message,False),'context':(ns['context'],False),'public key':(ns['public'].public_bytes_raw(),False),'signature':(signature,False)})
        public = MLDSA65PrivateKey.generate().public_key() if case=='wrong-key' else ns['public']
        try:
            public.verify(signature[:-1] if case=='truncated-signature' else signature,
                          message+b'!' if case=='changed-message' else message,
                          b'other-purpose' if case=='changed-context' else ns['context'])
        except InvalidSignature:
            yield step('Verify ML-DSA', 'Cryptographic verification rejected the altered input.',status='REJECT'); return
        yield step('Verify ML-DSA', 'Signature is valid relative to this configured public key.',status='PASS')
        yield step('Release policy', 'Teaching policy requires exact version 9 for this fixed-format message; a valid old signature is insufficient.', status='REJECT' if case=='old-version' else 'PASS')
    elif session == 12:
        from cryptography.hazmat.primitives.keywrap import aes_key_unwrap, aes_key_wrap, InvalidUnwrap
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        from cryptography.exceptions import InvalidTag
        yield step('Inspect envelope', 'DEK and KEKs are disposable local secrets. Ciphertext and wrapped DEK are separate objects.', {'wrapped DEK':(ns['wrapped_old'],False),'ciphertext':(ns['ciphertext'],False),'DEK':(ns['dek'],True),'old KEK':(ns['kek_old'],True),'new KEK':(ns['kek_new'],True)})
        try:
            dek = aes_key_unwrap(ns['kek_new'] if case=='wrong-kek' else ns['kek_old'],ns['wrapped_old'])
        except InvalidUnwrap:
            yield step('Unwrap DEK', 'Wrong KEK rejected by AES Key Wrap.',status='REJECT'); return
        yield step('Unwrap DEK', 'Recovered DEK matches original.',{'recovered DEK':(dek,True)},'PASS')
        if case in ('rewrap','stolen-old-backup'):
            wrapped = aes_key_wrap(ns['kek_new'],dek)
            yield step('Rotate wrapper', 'New KEK wraps the same DEK. Bulk ciphertext is unchanged.',{'new wrapped DEK':(wrapped,False)})
        try:
            plain = AESGCM(dek).decrypt(ns['nonce'],ns['ciphertext'],ns['context']+(b'!' if case=='changed-context' else b''))
        except InvalidTag:
            yield step('Authenticate data', 'Changed expected context rejected.',status='REJECT'); return
        yield step('Decrypt historical copy' if case=='stolen-old-backup' else 'Decrypt data',
                   'Old KEK plus old wrapped copy still reveals plaintext after rewrap.' if case=='stolen-old-backup' else 'AEAD accepted the record and context.', {'plaintext':(plain,False)},'EXPOSED' if case=='stolen-old-backup' else 'PASS')
    elif session == 13:
        principal = 'key-operator' if case=='operator-decrypt' else 'archive-reader'
        tenant = 'tenant-other' if case=='wrong-tenant' else 'tenant-acme'
        yield step('Authenticated caller assumption', 'Policy simulation only. Compromise does not change the authenticated identity string.',{'principal':(principal,False),'tenant':(tenant,False)})
        grant = ('archive-reader','decrypt','tenant-acme')
        saved = set(ns['grants'])
        try:
            if case=='revoked-grant': ns['grants'].discard(grant)
            allowed = ns['authorize'](principal,'decrypt',tenant,'interactive-teaching-request')
        finally:
            ns['grants'].clear(); ns['grants'].update(saved)
        yield step('Authorization and audit', 'Temporary policy edits restored after this trial.',{'latest audit event':(ns['audit'][-1],False)},'PASS' if allowed else 'REJECT')
        if allowed:
            yield step('Interpret allowed use', 'A compromised authorized reader can still request its scoped plaintext; key non-exportability does not prevent this.',status='EXPOSED' if case=='compromised-reader' else 'LIMIT')
    elif session == 14:
        model = {p:set(a) for p,a in ns['plaintext_access'].items()}
        principal = 'worker-acme' if case=='broaden-worker' else case
        if case=='broaden-worker': model[principal].add('document-other')
        yield step('Declared design', 'Explicit assumption model, not discovered permissions or an escalation analysis.',{'principal':(principal,False),'access map':({p:sorted(a) for p,a in model.items()},False)})
        try:
            exposed = ns['exposed_after_compromise']([principal],model)
        except ValueError as error:
            yield step('Evaluate scope',str(error),status='UNKNOWN'); return
        yield step('Modeled plaintext reach', 'An empty set does not rule out metadata theft, deletion or escalation.',{'exposed assets':(sorted(exposed),False)},'EXPOSED' if exposed else 'NO MODELED PLAINTEXT')
    elif session == 15:
        profile = 'record-v1' if case in ('legacy-read','legacy-write') else 'unknown' if case=='unknown-profile' else 'record-v2'
        operation = 'read' if case in ('legacy-read','unknown-profile') else 'write'
        yield step('Trusted policy', 'Profile routing model; not authenticated format negotiation.',{'policy':(ns['policy'],False),'request':((operation,profile),False)})
        try:
            provider = ns['select_profile'](profile,operation,ns['policy'])
        except ValueError as error:
            yield step('Select provider',str(error),status='REJECT'); return
        yield step('Select provider','Allowed under explicit read/write policy.',{'provider':(provider,False)},'PASS')
        evidence = dict(ns['evidence'])
        if case=='backup-not-ready': evidence['backups_recoverable']=False
        allowed = ns['can_retire'](evidence)
        yield step('Retirement gate', 'Boolean assertions require actual evidence and owner review.',{'evidence':(evidence,False)},'READY' if allowed else 'BLOCKED')
        if case=='retire':
            try: ns['select_profile']('record-v1','read',ns['retired_policy'])
            except ValueError:
                yield step('Retired reader', 'Old reads now reject; restore dependencies must have been resolved.',status='REJECT')
    elif session == 16:
        from graphlib import TopologicalSorter, CycleError
        dependencies = {k:set(v) for k,v in ns['dependencies'].items()}
        durations = dict(ns['duration'])
        if case=='verifier-delay': durations['verifier upgrade'] += parameter
        if case=='transport-delay': durations['transport pilot'] += parameter
        if case=='cycle': dependencies['inventory'].add('rollout')
        yield step('Planning assumptions', 'Invented months, unlimited parallel capacity; no quantum arrival forecast.', {'durations':(durations,False),'dependencies':({k:sorted(v) for k,v in dependencies.items()},False)})
        try: order = list(TopologicalSorter(dependencies).static_order())
        except CycleError:
            yield step('Order dependencies','Circular prerequisites prevent a valid order.',status='REJECT'); return
        finish = {}
        for task in order:
            start = max((finish[p] for p in dependencies[task]),default=0)
            finish[task] = start+durations[task]
            yield step(task,f'Start {start}; duration {durations[task]}; finish {finish[task]} months.',status='CALCULATED')
        yield step('Rollout finish',f'{finish["rollout"]} months under these assumptions. Identify the controlling prerequisite before changing budget or staffing.',{'finish times':(finish,False)},'PLAN')


def print_teaching_trace(session, namespace, case, parameter=10):
    rows = list(teaching_steps(session,namespace,case,parameter))
    for row in rows:
        print(row['step'], '|', row['status'], '|', row['explanation'])
    return rows


def teaching_panel(session, namespace):
    import ipywidgets as widgets
    from IPython.display import display, HTML
    case = widgets.Dropdown(options=TEACHING_CASES[session],description='Scenario:')
    parameter = widgets.IntSlider(value=10,min=0,max=40,description='H (years):' if session==8 else 'Delay months:')
    if session not in (8,16): parameter.layout.display='none'
    secret = widgets.Checkbox(value=False,description='Reveal disposable secrets',indent=False)
    advance = widgets.Button(description='Next step',button_style='info')
    reset_button = widgets.Button(description='Reset experiment')
    all_button = widgets.Button(description='Run all steps')
    inspect_button = widgets.Button(description='Print revealed objects')
    output, inspection = widgets.Output(), widgets.Output()
    state={'rows':[],'iterator':None}

    def render():
        output.clear_output(wait=True)
        with output:
            style='border:1px solid #839aaa;padding:8px;white-space:normal;overflow-wrap:anywhere;vertical-align:top'
            rows=''.join('<tr>'+''.join(f'<td style="{style}">{escape(str(row[k]))}</td>' for k in ('step','status','explanation'))+'</tr>' for row in state['rows'])
            display(HTML(f'<table style="width:100%;table-layout:fixed;border-collapse:collapse"><tr><th>Step</th><th>Observation</th><th>Explanation</th></tr>{rows}</table>'))
            print('Predict before Next step. Completed traces do not automatically imply security acceptance.')

    def reset(_=None):
        state['rows']=[]
        state['iterator']=iter(teaching_steps(session,namespace,case.value,parameter.value))
        advance.disabled=False
        secret.value=False
        inspection.clear_output()
        render()

    def next_step(_=None):
        inspection.clear_output()
        try: state['rows'].append(next(state['iterator']))
        except StopIteration: advance.disabled=True
        render()

    def run_all(_):
        state['rows'].extend(state['iterator'])
        advance.disabled=True
        inspection.clear_output()
        render()

    def inspect(_):
        inspection.clear_output(wait=True)
        with inspection:
            for row in state['rows']:
                for label,(value,sensitive) in row['artifacts'].items():
                    print('\n'+row['step']+' / '+label)
                    if sensitive and not secret.value:
                        print('[hidden disposable secret; enable reveal and print again]'); continue
                    if isinstance(value,bytes):
                        print('Length:',len(value),'bytes; SHA-256:',hashlib.sha256(value).hexdigest())
                        print('Hex:',value.hex())
                        if not sensitive and label in ('message','context','plaintext'): print('Bytes:',repr(value))
                    else: print(value)
    advance.on_click(next_step); reset_button.on_click(reset)
    all_button.on_click(run_all); inspect_button.on_click(inspect)
    case.observe(reset,names='value'); parameter.observe(reset,names='value')
    secret.observe(lambda _: inspection.clear_output(),names='value')
    display(widgets.VBox([widgets.HBox([case,parameter]),widgets.HBox([advance,all_button,reset_button]),output,secret,inspect_button,inspection]))
    reset()
    return dict(case=case,parameter=parameter,secret=secret,next=advance,reset=reset_button,all=all_button,inspect=inspect_button,state=state)


from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives.asymmetric.mlkem import MLKEM768PrivateKey
alice_x, bob_x = X25519PrivateKey.generate(), X25519PrivateKey.generate()
zx_a = alice_x.exchange(bob_x.public_key())
zx_b = bob_x.exchange(alice_x.public_key())
bob_pq = MLKEM768PrivateKey.generate()
zp_a, ct = bob_pq.public_key().encapsulate()
zp_b = bob_pq.decapsulate(ct)
suite = b'TEACHING-ONLY:X25519+ML-KEM-768:v1'
transcript = (suite + alice_x.public_key().public_bytes_raw()
              + bob_x.public_key().public_bytes_raw()
              + bob_pq.public_key().public_bytes_raw() + ct)
def teaching_combiner(classical, pq, context):
    if len(classical) != 32 or len(pq) != 32:
        raise ValueError('Both fixed-length contributions are required')
    return derive_day2(classical + pq, context)
key_a = teaching_combiner(zx_a, zp_a, transcript)
key_b = teaching_combiner(zx_b, zp_b, transcript)
assert key_a == key_b
assert key_a != teaching_combiner(zx_a, bytes(32), transcript)
assert key_a != teaching_combiner(bytes(32), zp_a, transcript)
assert key_a != teaching_combiner(zx_a, zp_a, transcript + b'changed')
expect_rejection(lambda: teaching_combiner(zx_a, b'', transcript), ValueError)
print('PASS: teaching combination depends on both secrets and exact context')

def require_hybrid(selected, authenticated, required=True):
    if not authenticated:
        raise ValueError('Unauthenticated negotiation')
    if required and selected != 'approved-hybrid-profile':
        raise ValueError('Local minimum policy not met')
    return selected
assert require_hybrid('approved-hybrid-profile', True) == 'approved-hybrid-profile'
expect_rejection(lambda: require_hybrid('classical-only', True), ValueError)
expect_rejection(lambda: require_hybrid('approved-hybrid-profile', False), ValueError)
print('PASS: minimum policy rejects downgrade and unauthenticated selection')

teaching_controls = teaching_panel(10, globals())

teaching_rows = print_teaching_trace(10, globals(), 'zero-pq-contribution')
assert len(teaching_rows) >= 2
print('PASS: Session 10 teaching trace completed')
print("PASS: completed session-10-hybrid-key-establishment demonstrations; learner status is reported separately")
