# Generated by scripts/build_session04.py from the Session 4 lesson.

import secrets
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa, padding

bob_rsa = rsa.generate_private_key(public_exponent=65537, key_size=3072)
content_key = secrets.token_bytes(32)

def oaep_parameters():
    return padding.OAEP(mgf=padding.MGF1(hashes.SHA256()),
                        algorithm=hashes.SHA256(), label=None)

wrapped_key = bob_rsa.public_key().encrypt(content_key, oaep_parameters())
wrapped_again = bob_rsa.public_key().encrypt(content_key, oaep_parameters())
assert wrapped_key != wrapped_again
assert bob_rsa.decrypt(wrapped_key, oaep_parameters()) == content_key
try:
    bob_rsa.public_key().encrypt(b"x" * 319, oaep_parameters())
except ValueError:
    pass
else:
    raise AssertionError("Oversized OAEP input unexpectedly accepted")
print("PASS: RSA-OAEP transports a short key, is randomized, and rejects oversized input.")

from cryptography.hazmat.primitives.asymmetric.x25519 import (
    X25519PrivateKey, X25519PublicKey,
)

alice_private = X25519PrivateKey.generate()
bob_private = X25519PrivateKey.generate()
alice_public = alice_private.public_key().public_bytes_raw()
bob_public = bob_private.public_key().public_bytes_raw()
assert len(alice_public) == len(bob_public) == 32
alice_secret = alice_private.exchange(X25519PublicKey.from_public_bytes(bob_public))
bob_secret = bob_private.exchange(X25519PublicKey.from_public_bytes(alice_public))
assert alice_secret == bob_secret
assert len(alice_secret) == 32
print("PASS: Alice and Bob compute the same X25519 secret from public contributions.")

try:
    alice_private.exchange(X25519PublicKey.from_public_bytes(b"\x00" * 32))
except ValueError:
    pass
else:
    raise AssertionError("Unusable X25519 contribution unexpectedly accepted")
print("PASS: unusable X25519 input is rejected; never substitute a fallback key.")

from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.exceptions import InvalidTag

transcript = b"workshop-channel:v1|" + alice_public + bob_public
salt = secrets.token_bytes(32)

def traffic_key(secret, agreed_salt, exchange_transcript, direction):
    return HKDF(algorithm=hashes.SHA256(), length=32, salt=agreed_salt,
                info=exchange_transcript + b"|" + direction).derive(secret)

alice_send = traffic_key(alice_secret, salt, transcript, b"alice-to-bob")
bob_receive = traffic_key(bob_secret, salt, transcript, b"alice-to-bob")
bob_send = traffic_key(bob_secret, salt, transcript, b"bob-to-alice")
assert alice_send == bob_receive
assert alice_send != bob_send
invoice = b"invoice=7;amount=125;currency=USD"
nonce = secrets.token_bytes(12)
aad = b"workshop:v1|tenant=acme|invoice=7|direction=alice-to-bob"
ciphertext = AESGCM(alice_send).encrypt(nonce, invoice, aad)
assert AESGCM(bob_receive).decrypt(nonce, ciphertext, aad) == invoice
try:
    AESGCM(bob_send).decrypt(nonce, ciphertext, aad)
except InvalidTag:
    pass
else:
    raise AssertionError("Wrong-direction key unexpectedly accepted")
print("PASS: derived keys carry the invoice and reject the wrong direction.")

mallory_for_alice = X25519PrivateKey.generate()
mallory_for_bob = X25519PrivateKey.generate()
m_public_a = mallory_for_alice.public_key().public_bytes_raw()
m_public_b = mallory_for_bob.public_key().public_bytes_raw()
alice_view = b"workshop-channel:v1|" + alice_public + m_public_a
bob_view = b"workshop-channel:v1|" + m_public_b + bob_public
alice_to_m = alice_private.exchange(mallory_for_alice.public_key())
m_to_alice = mallory_for_alice.exchange(alice_private.public_key())
bob_to_m = bob_private.exchange(mallory_for_bob.public_key())
m_to_bob = mallory_for_bob.exchange(bob_private.public_key())
assert alice_to_m == m_to_alice
assert bob_to_m == m_to_bob
assert alice_to_m != bob_to_m

alice_fooled_key = traffic_key(alice_to_m, salt, alice_view, b"alice-to-bob")
mallory_read_key = traffic_key(m_to_alice, salt, alice_view, b"alice-to-bob")
bob_fooled_key = traffic_key(bob_to_m, salt, bob_view, b"alice-to-bob")
mallory_write_key = traffic_key(m_to_bob, salt, bob_view, b"alice-to-bob")
nonce_a, nonce_b = secrets.token_bytes(12), secrets.token_bytes(12)
alice_record = AESGCM(alice_fooled_key).encrypt(nonce_a, invoice, aad)
stolen = AESGCM(mallory_read_key).decrypt(nonce_a, alice_record, aad)
changed = stolen.replace(b"amount=125", b"amount=999")
relay_record = AESGCM(mallory_write_key).encrypt(nonce_b, changed, aad)
assert AESGCM(bob_fooled_key).decrypt(nonce_b, relay_record, aad) == changed
assert changed != invoice
print("PASS: simulated substitution lets Mallory read and alter data without breaking AEAD.")

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.exceptions import InvalidSignature

bob_identity = Ed25519PrivateKey.generate()
trusted_bob_verification_key = bob_identity.public_key()  # Simulated trusted provisioning.
statement = b"workshop-demo:bob-authentication:v1|" + transcript + salt
signature = bob_identity.sign(statement)
trusted_bob_verification_key.verify(signature, statement)  # Success returns None.
substituted_statement = b"workshop-demo:bob-authentication:v1|" + alice_view + salt
mallory_identity = Ed25519PrivateKey.generate()
for candidate_signature, candidate_statement in [
    (signature, substituted_statement),
    (mallory_identity.sign(statement), statement),
]:
    try:
        trusted_bob_verification_key.verify(candidate_signature, candidate_statement)
    except InvalidSignature:
        pass
    else:
        raise AssertionError("Invalid authentication statement unexpectedly accepted")
print("PASS: trusted signature verifies; substituted transcript and impostor signer fail.")

next_alice = X25519PrivateKey.generate()
next_bob = X25519PrivateKey.generate()
next_secret = next_alice.exchange(next_bob.public_key())
assert next_secret == next_bob.exchange(next_alice.public_key())
assert next_secret != alice_secret
# A retained RSA private key still decrypts yesterday's recorded key transport.
assert bob_rsa.decrypt(wrapped_key, oaep_parameters()) == content_key
print("PASS: fresh exchange changes the secret; retained RSA key decrypts recorded transport.")
